version: '3'
services:
  react-app:
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - "../angular-app/:/usr/src/app/"
    tty: true
    environment:
      - NODE_ENV=development
