version: '3'
services:
  react-app:
    container_name: pwa_react_app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "../../react-app/:/usr/src/app/"
    tty: true
    environment:
      - NODE_ENV=development
